config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :flats
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :price_per_night, :number_of_guests, numericality: { only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
    # @flat = flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
    redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @flat = flat.find(params[:id])
  end

  def update
    # @flat = flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    # @flat = flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit flat</h1>
<%= form_with model: @flat do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.label :address %>
  <%= t.text_field :address %>
  <%= t.label :description %>
  <%= t.text_field :description %>
  <%= t.label :price_per_night %>
  <%= t.text_field :price_per_night %>
  <%= t.label :number_of_guests %>
  <%= t.text_field :number_of_guests %>
  <%= t.submit %>
<% end %>

app/views/flats/index.html.erb
<% count = @flats.length %>

<div class="container">
  <h1>My flats(<%= count %>)</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <img src="<%= flat.image_url %>" class="card-img-top" alt="Flat Image">
          <div class="card-body">
            <h4 class="card-title"><strong><%= link_to flat.name, flat_path(flat) %></strong></h4>
            <p><%= flat.address %></p>
            <div class="d-flex justify-content-start">
              <p><%= flat.price_per_night %> <i class="fa-solid fa-euro-sign"></i> </p>
              <p><%= flat.number_of_guests %> <i class="fa-solid fa-user fa-spin-pulse pp"></i></p>
            </div>
          </div>
          <div class="card-footer">
            <%= link_to "Delete", flat_path(flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Add new", new_flat_path, class: "btn btn-primary" %>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>
<%= form_with model: @flat do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.label :address %>
  <%= t.text_field :address %>
  <%= t.label :description %>
  <%= t.text_field :description %>
  <%= t.label :price_per_night %>
  <%= t.text_field :price_per_night %>
  <%= t.label :number_of_guests %>
  <%= t.text_field :number_of_guests %>
  <%= t.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
      <p><%= @flat.description %></p>
      <p><i class="fa-solid fa-euro-sign"></i> <%= @flat.price_per_night %></p>
      <p ><i class="fa-solid fa-user fa-spin-pulse"></i> <%= @flat.number_of_guests %></p>
    </div>
    <div class="card-footer">
      <%= link_to "Back to list", flats_path, class: "btn btn-secondary btn-sm" %>
      <%= link_to "Edit", edit_flat_path(@flat), class: "btn btn-primary btn-sm" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  simple airbnb
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>